mode: include
allowed_category_codes:
  - CARTINJ_COMPAT
  - CARTINJ_ORIG
  - CARTINJ_PRNTHD
  - CARTLAS_COMPAT
  - CARTLAS_COPY
  - CARTLAS_ORIG
  - CARTLAS_PRINT
  - CARTLAS_TNR
  - CARTMAT_CART
  - DEV_DEV
  - DRM_CRT
  - DRM_UNIT
  - PARTSPRINT_THERBLC
  - PARTSPRINT_THERELT

enforce_title_prefixes: false
require_catalog_url: true

include_title_prefixes:
  - Картридж
  - Тонер-картридж
  - Тонер-катридж
  - Принт-картридж
  - Копи-картридж
  - Драм-юнит
  - Драм-картридж
  - Фотобарабан
  - Барабан
  - Девелопер
  - Термоблок
  - Термоэлемент
  - Нагревательный
  - Блок
  - Контейнер
  - Комплект
  - Набор
  - Носитель
  - Печатающая
  - Тонер
