supplier: vtt
adapter_cleans_params: true

key_rules:
  banned_exact:
    - Артикул
    - Штрих-код
    - Вендор
    - Категория
    - Подкатегория
    - Категория VTT
    - SKU
    - UPC
    - EAN
  aliases:
    OEM-номер: Партномер
    Партс-номер: Партномер
    Каталожный номер: Партномер

allow_keys:
  common:
    - Тип
    - Для бренда
    - Партномер
    - Коды расходников
    - Совместимость
    - Технология печати
    - Цвет
    - Ресурс
