name: build_price_seo

on:
  workflow_dispatch:
  schedule:
    # 07:00 Asia/Almaty == 02:00 UTC (UTC+5)
    - cron: "0 2 * * *"

concurrency:
  group: build_price_seo_${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Almaty schedule gate
        id: gate
        run: |
          python - <<'PY'
          from datetime import datetime, timedelta
          now_utc = datetime.utcnow()
          # Алматы сейчас UTC+5
          now_alm = now_utc + timedelta(hours=5)
          should = 'yes' if now_alm.hour == 7 else 'no'
          print(f"::notice::Almaty now: {now_alm:%Y-%m-%d %H:%M:%S}, should_run={should}")
          with open("${GITHUB_OUTPUT}", "a") as f:
              f.write(f"run={should}\n")
          PY

      - uses: actions/setup-python@v5
        if: ${{ github.event_name == 'workflow_dispatch' || steps.gate.outputs.run == 'yes' }}
        with:
          python-version: "3.11"

      - name: Run SEO enhancer (price_seo.py)
        if: ${{ github.event_name == 'workflow_dispatch' || steps.gate.outputs.run == 'yes' }}
        run: |
          set -e
          python scripts/price_seo.py

      - name: Commit & push docs/price_seo.yml
        if: ${{ github.event_name == 'workflow_dispatch' || steps.gate.outputs.run == 'yes' }}
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/price_seo.yml docs/.nojekyll || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else:
            git commit -m "chore(seo): build docs/price_seo.yml"
            git pull --rebase origin "$BRANCH_NAME" || true
            git push origin "$BRANCH_NAME"
          fi

      - name: Print URLs (Pages + RAW/CDN)
        if: ${{ github.event_name == 'workflow_dispatch' || steps.gate.outputs.run == 'yes' }}
        env:
          OWNER: ${{ github.repository_owner }}
          REPO_SLUG: ${{ github.repository }}
        run: |
          set -e
          REPO="${REPO_SLUG#*/}"
          echo "PAGES: https://${OWNER}.github.io/${REPO}/price_seo.yml"
          echo "RAW:   https://raw.githubusercontent.com/${OWNER}/${REPO}/main/docs/price_seo.yml"
          echo "CDN1:  https://cdn.jsdelivr.net/gh/${OWNER}/${REPO}@main/docs/price_seo.yml"
          echo "CDN2:  https://cdn.statically.io/gh/${OWNER}/${REPO}/main/docs/price_seo.yml"
