# .github/workflows/commit_copyline_photo_test.yml
name: commit_copyline_photo_test

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'scripts/enrich_copyline_photos_test.py'
      - '.github/workflows/commit_copyline_photo_test.yml'

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Build photo test YML
        env:
          OUTPUT_ENCODING: windows-1251
        run: |
          python scripts/enrich_copyline_photos_test.py
          test -f docs/copyline_photo_test.yml

      - name: Upload artifact (photo test)
        uses: actions/upload-artifact@v4
        with:
          name: copyline-photo-test
          path: docs/copyline_photo_test.yml
          if-no-files-found: error

      - name: Commit & push photo test YML (separate)
        shell: bash
        run: |
          set -e
          BRANCH="${GITHUB_REF_NAME:-main}"

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [ -f docs/copyline_photo_test.yml ]; then
            git add docs/copyline_photo_test.yml
          fi

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Copyline photo test: update docs/copyline_photo_test.yml"
          git pull --rebase origin "$BRANCH" || git rebase --abort
          git push origin "$BRANCH"
