name: copyline_variant_b

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'scripts/build_copyline_index.py'
      - 'scripts/enrich_copyline_photos_from_index.py'
      - 'docs/copyline_category_urls.txt'
      - '.github/workflows/copyline_variant_b.yml'
      - 'docs/copyline.yml'
  schedule:
    - cron: "0 2 * * *"   # ежедневно 02:00 UTC

concurrency:
  group: copyline-variant-b
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build-index-and-enrich:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      # Шаг 1: построить/обновить индекс карточек -> фото
      - name: Build Copyline photo index (Variant B)
        env:
          URLS_FILE: docs/copyline_category_urls.txt
          INDEX_PATH: docs/copyline_photo_index.json
          REQUEST_DELAY_MS: 700
          BACKOFF_MAX_MS: 12000
          FLUSH_EVERY_N: 25
        run: |
          python scripts/build_copyline_index.py
          test -f docs/copyline_photo_index.json

      # Шаг 2: обогатить YML фотографиями из индекса
      - name: Enrich YML from index (Variant B)
        env:
          YML_PATH: docs/copyline.yml
          OUT_FILE: docs/copyline.yml
          INDEX_PATH: docs/copyline_photo_index.json
          OUTPUT_ENCODING: windows-1251
          REQUEST_DELAY_MS: 700
          BACKOFF_MAX_MS: 12000
          MAX_RETRIES: 3
        run: |
          python scripts/enrich_copyline_photos_from_index.py
          test -f docs/copyline.yml

      - name: Commit & push changes (index + yml)
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Добавляем только существующие файлы
          [ -f docs/copyline_photo_index.json ] && git add docs/copyline_photo_index.json || true
          [ -f docs/copyline.yml ] && git add docs/copyline.yml || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Copyline: Variant B (index + enrich)"
            git pull --rebase || true
            git push
          fi
