name: enrich_copyline_photos_list

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'scripts/scrape_copyline_photos_by_list.py'
      - 'docs/copyline_articles.txt'
      - '.github/workflows/enrich_copyline_photos_list.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run scraper (by list) -> docs/copyline.yml (для GitHub Pages)
        env:
          ARTICLES_FILE: docs/copyline_articles.txt
          OUT_FILE: docs/copyline.yml
          OUTPUT_ENCODING: windows-1251
          REQUEST_DELAY_MS: 600
        run: |
          python scripts/scrape_copyline_photos_by_list.py
          test -f docs/copyline.yml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: copyline-yml
          path: docs/copyline.yml
          if-no-files-found: error

      - name: Commit & push if changed
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/copyline.yml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update: copyline photos (by list) -> docs/copyline.yml"
            git pull --rebase
            git push
          fi
