name: scrape_copyline_category

on:
  workflow_dispatch:
    inputs:
      CATEGORY_URL:
        description: "URL категории Copyline"
        required: true
        default: "https://copyline.kz/goods/toner-cartridges-brother.html"
  schedule:
    - cron: "0 2 * * *"   # ежедневно 02:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Scrape category → YML
        env:
          CATEGORY_URL: ${{ github.event.inputs.CATEGORY_URL }}
          OUT_FILE: docs/copyline.yml
          OUTPUT_ENCODING: windows-1251
          REQUEST_DELAY_MS: 700
          PAGE_TIMEOUT_S: 30
          MAX_PAGES: 50
          MIN_BYTES: 2500
        run: |
          python scripts/scrape_copyline_category.py
          ls -l docs || true
          test -f docs/copyline.yml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: copyline-yml
          path: docs/copyline.yml
          if-no-files-found: error

      - name: Commit & push YML if changed
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A docs/copyline.yml
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update Copyline YML (category scrape)"
            git push
          else
            echo "No changes to commit."
          fi
